services:
  backend:
    build: ./back
    ports: ["3030:3030"]  # Host acessa localhost:3030
    env_file: ./back/.env

  frontend:
    build: ./front
    ports: ["5173:5173"]
    env_file: ./front/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux fix
    depends_on:
      - backend